release:
	dmcs DRFCSharp/*.cs -pkg:dotnet -r:DRFCSharp/bin/Release/MathNet.Numerics.dll -r:DRFCSharp/bin/Release/zlib.net.dll -out:DRFCSharp/bin/Release/DRFCSharp.exe

debug:
	dmcs DRFCSharp/*.cs -debug -pkg:dotnet -r:DRFCSharp/bin/Debug/MathNet.Numerics.dll -r:DRFCSharp/bin/Debug/zlib.net.dll -out:DRFCSharp/bin/Debug/DRFCSharp.exe
